from telegram_bots.modules.booking.repository.api_repository.realisation import BookingRepositoryRealisationDatabase
from telegram_bots.modules.booking.repository.api_repository.abstraction import BookingRepositoryAbstractionAsync


booking_repository_realisation_database = BookingRepositoryRealisationDatabase()
booking_repository_abstraction = BookingRepositoryAbstractionAsync(booking_repository_realisation_database)
