"""empty message

Revision ID: 15faa1496b93
Revises: 
Create Date: 2022-09-20 11:38:16.174846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15faa1496b93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_event', sa.Time(), nullable=True),
    sa.Column('end_event', sa.Time(), nullable=True),
    sa.Column('delta_time', sa.Time(), nullable=True),
    sa.Column('default_services', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ip_service', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_event', sa.String(), nullable=True),
    sa.Column('day_start', sa.Date(), nullable=False),
    sa.Column('day_end', sa.Date(), nullable=False),
    sa.Column('start_event', sa.Time(), nullable=True),
    sa.Column('end_event', sa.Time(), nullable=True),
    sa.Column('weekdays', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('many_day', sa.ARRAY(sa.Date()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_event', 'day_start', 'day_end', 'start_event', 'end_event')
    )
    op.create_table('global_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('myservice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_service', sa.String(), nullable=True),
    sa.Column('price_service', sa.Float(), nullable=True),
    sa.Column('duration', sa.Time(), nullable=True),
    sa.Column('max_booking', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_service')
    )
    op.create_table('mystaff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_staff', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_this_company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_client', sa.String(), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('phone_num', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('all_booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('signup_event', sa.Integer(), nullable=True),
    sa.Column('signup_user', sa.Integer(), nullable=True),
    sa.Column('signup_service', sa.Integer(), nullable=True),
    sa.Column('signup_staff', sa.Integer(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['signup_event'], ['event_company.id'], ),
    sa.ForeignKeyConstraint(['signup_service'], ['myservice.id'], ),
    sa.ForeignKeyConstraint(['signup_staff'], ['mystaff.id'], ),
    sa.ForeignKeyConstraint(['signup_user'], ['users_this_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connect_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['global_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('count_service_this_event', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['myservice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'service_id')
    )
    op.create_table('service_staff_connect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['myservice.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['mystaff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'staff_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_staff_connect')
    op.drop_table('service_event')
    op.drop_table('connect_department')
    op.drop_table('all_booking')
    op.drop_table('users_this_company')
    op.drop_table('mystaff')
    op.drop_table('myservice')
    op.drop_table('global_users')
    op.drop_table('event_company')
    op.drop_table('department_info')
    op.drop_table('default_setting')
    # ### end Alembic commands ###
