from telegram_bots.modules.register.repository.api_repository.repository_realisation import (
    RegisterRepositoryRealisationDatabaseAsync, RegisterRepositoryRealisationDatabaseSync
)


register_repository_async = RegisterRepositoryRealisationDatabaseAsync()
register_repository_sync = RegisterRepositoryRealisationDatabaseSync()
