"""empty message

Revision ID: 00daf20797ea
Revises: e369ba02f2c0
Create Date: 2022-09-03 16:51:07.519654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00daf20797ea'
down_revision = 'e369ba02f2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event_company', ['id', 'name_event', 'day_start', 'day_end', 'start_event', 'end_event'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_company', type_='unique')
    # ### end Alembic commands ###
