"""empty message

Revision ID: a54eb45274c2
Revises: 00daf20797ea
Create Date: 2022-09-04 14:05:42.754892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54eb45274c2'
down_revision = '00daf20797ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_booking', sa.Column('day', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('all_booking', 'day')
    # ### end Alembic commands ###
