"""empty message

Revision ID: c9b1cc79420a
Revises: 23baa15d55bb
Create Date: 2022-05-22 21:35:41.458082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b1cc79420a'
down_revision = '23baa15d55bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_company', sa.Column('delta', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_company', 'delta')
    # ### end Alembic commands ###
