"""empty message

Revision ID: e1d2e07f83d5
Revises: e8b4e58b6a1c
Create Date: 2022-09-03 16:33:26.604664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d2e07f83d5'
down_revision = 'e8b4e58b6a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_company', sa.Column('many_day', sa.ARRAY(sa.Date()), nullable=True))
    op.add_column('myservice', sa.Column('max_booking', sa.Integer(), nullable=True))
    op.drop_column('myservice', 'max_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myservice', sa.Column('max_book', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('myservice', 'max_booking')
    op.drop_column('event_company', 'many_day')
    # ### end Alembic commands ###
