"""empty message

Revision ID: e369ba02f2c0
Revises: e1d2e07f83d5
Create Date: 2022-09-03 16:40:14.711776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e369ba02f2c0'
down_revision = 'e1d2e07f83d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_company', sa.Column('weekdays', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_company', 'weekdays')
    # ### end Alembic commands ###
