"""empty message

Revision ID: e8b4e58b6a1c
Revises: ab3e5df100eb
Create Date: 2022-09-02 16:13:58.879039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8b4e58b6a1c'
down_revision = 'ab3e5df100eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_company', sa.Column('day_start', sa.Date(), nullable=False))
    op.add_column('event_company', sa.Column('day_end', sa.Date(), nullable=False))
    op.drop_column('event_company', 'delta')
    op.drop_column('event_company', 'day')
    op.add_column('myservice', sa.Column('duration', sa.Time(), nullable=True))
    op.add_column('myservice', sa.Column('max_book', sa.Integer(), nullable=True))
    op.add_column('service_event', sa.Column('count_service_this_event', sa.JSON(), nullable=False))
    op.create_unique_constraint(None, 'service_event', ['id', 'event_id', 'service_id'])
    op.drop_column('service_event', 'quantity')
    op.create_unique_constraint(None, 'service_staff_connect', ['id', 'service_id', 'staff_id'])
    op.create_unique_constraint(None, 'users_this_company', ['tg_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_this_company', type_='unique')
    op.drop_constraint(None, 'service_staff_connect', type_='unique')
    op.add_column('service_event', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_event', type_='unique')
    op.drop_column('service_event', 'count_service_this_event')
    op.drop_column('myservice', 'max_book')
    op.drop_column('myservice', 'duration')
    op.add_column('event_company', sa.Column('day', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('event_company', sa.Column('delta', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('event_company', 'day_end')
    op.drop_column('event_company', 'day_start')
    # ### end Alembic commands ###
